Attribute VB_Name = "Header"
'定数'
'データシート'
Public Const dataSheetName = "データ"  'シート名'
'行'
Const initDataLine = 2          'データの最初の行'
'列'
Const noRow = 1                 'Noの列(A列)'
Public Const rawRow = 2                '呼吸音の列(B列)'
Const rawSnoreRow = 3           'いびき音の列(C列)'
Const rawMovAvrRow = 4          '呼吸音の移動平均の列(D列)'
Const snoreStateRow = 5         'いびき判定結果の入った列(E列)'
Const apneaStateRow = 6         '無呼吸判定結果の入った列(F列)'
Const acceXRow = 7              '加速度(X)の入った列(G列)'
Const acceYRow = 8              '加速度(Y)の入った列(H列)'
Const acceZRow = 9              '加速度(Z)の入った列(I列)'
Const retAcceRow = 10           '向き(J列)'


'結果シート'
Public Const retSheetName = "結果"     'シート名'
'行'
Const initRetLine = 7           '結果が入力される最初の行'
'列'
Public Const retStartTimeRow = 2       '判定時刻の列(B列)'
Const retStopTimeRow = 3        '停止時刻の列(C列)'
Const retContinuTimeRow = 4     '継続時間の列(D列)'
Const retTypeRow = 5            '種別の列(E列)'
Const retStartFromStopTimeRow = 6   '前回停止から今回発生までの時間の列(F列)'
Const retRemarkRow = 7          '備考の列(F列)'
'入力文字'
Const snore = "いびき"
Const apnea = "無呼吸"
